baseURL = "https://jnog.dev/"
languageCode = "en-us"
title = "Jonathan Nogueira"
copyright = "Copyright Â© 2026 Jonathan Nogueira"

[params]
  homeSubtitle = "Software Engineer // ğŸ‘¨â€ğŸ’»"
  description = "Jonathan Nogueira's personal website"
  keywords = "homepage"
  EnableThemeToggle = true

[params.logo]
  logoText = "jnog"
  logoCursorColor = "cyan"

[params.footer]
  copyright = true

[[params.social]]
  name = "email"
  url = "mailto:jonathan@jnog.dev"
[[params.social]]
  name = "github"
  url = "https://github.com/jnog"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jonathan-nogueira"
